FROM ubuntu:16.04

MAINTAINER Jack Chen <18468289@qq.com>

# 将本地文件添加到容器中，tar类型文件会自动解压(网络压缩资源不会被解压)，可以访问网络资源，类似wget
ADD sources.list /etc/apt/
# COPY：功能类似ADD，但是是不会自动解压文件，也不能访问网络资源


RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y nodejs

CMD node -v

# echo "{\"registry-mirrors\": [\"https://nj4c27p4.mirror.aliyuncs.com\"],\"insecure-registries\" : [\"192.168.0.86:8000\",\"harbor.faceunity.com\",\"192.168.0.35:5000\",\"fiskzeroun.faceunity.com:4000\",\"122.224.254.235:5000\",\"fiskzeroun.faceunity.com:5000\",\"192.168.0.86:5000\"],\"runtimes\": {\"nvidia\": {\"path\": \"nvidia-container-runtime\",\"runtimeArgs\": []}}}" > daemon.json && \

# COPY ./node_modules /root/worker/node_modules

# COPY . /root/app

# WORKDIR /root/app

# RUN npm i

# ENV LD_LIBRARY_PATH /root/worker/data:/root/worker/libs

# CMD node index.js